language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - nightly


before_script :
  - composer install --dev

script:
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 src tests
  - ./vendor/bin/phpunit

notifications:
  email:
    - matthew@baggett.me
