name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 8.0
      - uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml.dist
          php_version: 8.0
          version: 9